### ISSUE TITLE
Incorrect plugin header.

### ISSUE THREAD

**Issue by HomAfromPTZ** [mtekk/Breadcrumb-NavXT#100]
"Domainpath" and "Textdomain" lines in breadcrumb-navxt.php header are incorrect, according to the Codex they must be spaced:

```
Text Domain: breadcrumb-navxt
Domain Path: /languages
```

At this time on WP "Plugins" page you can see that any other language except EN don't work, because of this problem.

**Comment by mtekk** [comment]
Thanks for reporting that, it's fixed in the master branch and will make the next release (likely 5.2.1).

**Comment by HomAfromPTZ** [comment]
You're welcome.
