### ISSUE TITLE
Deprecated title_trim() called in class.bcn_breadcrumb_trail.php

### ISSUE THREAD

**Issue by thewebists** [mtekk/Breadcrumb-NavXT#102]
With debugging enabled on version 5.2.0 I get deprecated function notices for title_trim(), which is called from class.bcn_breadcrumb_trail.php.

No reason for a stable version release of the plugin to reference its own deprecated functions.

**Comment by toleabivol** [comment]
:+1:  :)

**Comment by mtekk** [comment]
Yes, there is a valid reason for a stable version release of a plugin to reference its own deprecated functions. The feature is deprecated, as are the functions that support it. The new way requires some CSS, which will not be automatically added or configured for end users. I'm not flat up removing the feature for a while (will likely be 5.5 or 6.0 when it is removed) to give people time to migrate before things break. See: http://mtekk.us/archives/guides/trimming-breadcrumb-title-lengths-with-css/

If you have enabled title trimming through the options, then this deprecation notice will be thrown. The only other alternate would be to use `_doing_it_wrong()`.
