### ISSUE TITLE
Root Level To Be Custom Post Type Post

### ISSUE THREAD

**Issue by Kyran1** [mtekk/Breadcrumb-NavXT#105]
Hi there, 

Firstly great plugin!

I am currently using your plugin but require the ability to add a custom post type post to be the root level of another custom post type. 

Do you think that this would be possible?

**Comment by mtekk** [comment]
If you do not need to use other things in your hierarchy (e.g. don't need taxonomy terms to show up in it for the CPT), then the best way of doing this is to change the CPT Hierarchy to 'Post Parent'. Then setup the parent<->child relationship manually (I'm sure there are plugins for this), Breadcrumb NavXT does not care about the post type when following 'Post Parent' hierarchies.
