### ISSUE TITLE
Add filter hook on root_id

### ISSUE THREAD

**Issue by hanenevanhoute** [mtekk/Breadcrumb-NavXT#108]
Hello,

I'd like to ask to the plugin devs if it would be possible to add a filter hook on the $root_id value.
Maybe with a code like this
$root_id = apply_filters( 'bcn_root_id', $root_id );

Thanks

**Comment by mtekk** [comment]
What is the use case for this? To me, it sounds like something that has other solutions, and you probably should not be programatically changing the root_id.

**Comment by mtekk** [comment]
I'm closing this as there is already a way to do this through the `bcn_before_fill` action, allowing you to programatically change the options, including the root id, just before the breadcrumb trail is generated.
