### ISSUE TITLE
Fix suggestion for making breadcrumbs work with Events Calendar Plugin

### ISSUE THREAD

**Issue by jflagarde** [mtekk/Breadcrumb-NavXT#125]
Line 928 in class.bcn_breadcrumb_trail.php
$this->do_post($GLOBALS['post']);
can give an error when the global post is "corrupted". It happens with custom post types used for example in https://wordpress.org/plugins/the-events-calendar/ where the event breadcrumb doesn't work.

A solution to this is simply to reset the global $post object with
wp_reset_postdata();
inserted right above line 928.

**Comment by mtekk** [comment]
The downside of adding `wp_reset_postdata()` to Breadcrumb NavXT is it will cause Breadcrumb NavXT to not be safe to call from within the loop. In the past, the solution has been to ensure `$post` is correct before invoking Breadcrumb NavXT.
