### ISSUE TITLE
Amazon like "all hierarchies" breadcrumb trails

### ISSUE THREAD

**Issue by mtekk** [mtekk/Breadcrumb-NavXT#141]
Per request here: https://wordpress.org/support/topic/multiple-breadcrumbs-amazon-style?replies=5

The idea is to have a single function handle generation of all breadcrumb trails (with some sort of filter to control) to a particular item.

**Comment by jeffmcneill** [comment]
I am also very interested in multiple breadcrumb trails. I'm using the order bender to set the primary category, so the single breadcrumb trail is being correctly generated, but there are multiple categories/subcategories which should be displayed as multiple breadcrumb trails. This is for books, which have multiple controlled vocabularies (but only a few). E.g.,

catalog > author > sun tzu > art of war
catalog > history > asia > china
catalog > history > military strategy

I am using nested categories for each of these, and they display well in a category widget. I need multiple breadcrumbs supported as well. Google breadcrumb structured data supports multiple breadcrumb trails.

**Comment by mtekk** [comment]
A quick update in regards to this. A product that implements this functionality, tentatively titled "Breadcrumb NavXT Attributes", is in the works. The initial implementation is done and I'm in the process of preparing it for release later this month.

**Comment by mtekk** [comment]
Breadcrumb NavXT Attributes has been released.
