### ISSUE TITLE
Fix typo in _taxonomy_referer 

### ISSUE THREAD

**Issue by emilyljohnson** [mtekk/Breadcrumb-NavXT#161]
> Allow the **refereing** page to influence the taxonomy selected for the hierarchy.

should be:

> Allow the **referring** page to influence the taxonomy selected for the hierarchy.

class.bcn_admin.php - line 500
class.bcn_admin.php - line 578

class.bcn_network_admin.php - line 572
class.bcn_network_admin.php - line 650

**Comment by mtekk** [comment]
Thank you for reporting this. It should now be fixed in the 'kayaker' branch and will make the 5.7.0 release.
