### ISSUE TITLE
How to set href link for home page in home template

### ISSUE THREAD

**Issue by prafullwizorbit** [mtekk/Breadcrumb-NavXT#189]
Hi
    This is home template: 
`<span property="itemListElement" typeof="ListItem"><a property="item" typeof="WebPage" title="Go to %title%." href="%link%" class="%type%"><span property="name">%htitle%</span></a><meta property="position" content="%position%">HOME</span>`

Result in showing HOME > pagelink like
But how to redirect this HOME anchor tag to home page url
Thanks

**Comment by mtekk** [comment]
For completeness, the `%link%` tag will be replaced by the appropriate URL for the resource. In the case of the home breadcrumb template, it will be replaced with the results of `get_home_url()`. If that function is not returning the proper URL, then WordPress doesn't fully know what is going on (read as you may be doing something custom and have not done everything needed for seamless functionality).
