### ISSUE TITLE
Can I show any post slug after page name in breadcrumb

### ISSUE THREAD

**Issue by prafullwizorbit** [mtekk/Breadcrumb-NavXT#192]
Hi
    I am facing a problem that is currently  i have a page that show some post in grid. 
Now breadcrumb show like Home > mainmenu > submenu 
but when i click on any post then breadcrumb show like Home > postslug
What I want after click on post it should be Home > mainmenu >submenu > postslug
can i do this with the help of NavXt plugin setting because i am not finding any solution for creating post page breadcrumb under its parent page. 

please suggest some help.
Thanks

**Comment by dharmdeep** [comment]
Yes 
      I have also same requirement, it will be interesting to know that how to connect post slug to its parent pages breadcrumbs like url home / main_menu / sub_menu / post_slug
Anyone have any idea.
Thanks

**Comment by mtekk** [comment]
You need to have "postslug" be a child of "submenu" for this to work out of the box with Breadcrumb NavXT. Then you can use the hierarchy type setting (set to "post parent") for the post type that "postslug" belongs to. Something like https://github.com/mtekk/Post-Parents can help with setting parents for regular posts.

**Comment by prafullwizorbit** [comment]
GREAT
Thanks a Lot :)
Its Working

**Comment by dharmdeep** [comment]
Its working also for me.
Thanks
