### ISSUE TITLE
How to remove Uncategorized from breadcrumb trail?

### ISSUE THREAD

**Issue by realuser** [mtekk/Breadcrumb-NavXT#194]
The bread crumbs for my blog posts show up as:

`Home > Blog > Uncategorized > New Acme Widget`
 
How can I remove the category "Uncategorized" so my post breadcrumbs appear as:

`Home > Blog > New Acme Widget`

Breadcrumb NavXT 6.0.4 on Wordpress 4.9.4

**Comment by mtekk** [comment]
If you are not using categories at all for your posts, under the Post Types tab in the Breadcrumb NavXT settings page, you can uncheck the "Post Hierarchy Display" setting and press "Save Changes". This will tell Breadcrumb NavXT to not include a category hierarchy in the breadcrumb trail for posts.

**Comment by realuser** [comment]
That worked thank you

**Comment by kingma-sbw** [comment]
> If you are not using categories at all for your posts, under the Post Types tab in the Breadcrumb NavXT settings page, you can uncheck the "Post Hierarchy Display" setting and press "Save Changes". This will tell Breadcrumb NavXT to not include a category hierarchy in the breadcrumb trail for posts (instances of the built in post post type).

We are unable to locate "Post Hierarchy Display" inst Breadcrumb NavXT settings page. Was this removed?

**Comment by mtekk** [comment]
The "Post Hierarchy Display" is still there, make sure you are in the "Post Types" tab of the Breadcrumb NavXT settings page.
