### ISSUE TITLE
URL Trim Failing for Select Tags

### ISSUE THREAD

**Issue by jrg94** [mtekk/Breadcrumb-NavXT#195]
I recently decided to simplify my site a bit by converting two categories to tags. Now, the breadcrumb throws the following error for those tags:

```
Warning: trim() expects parameter 1 to be string, 
object given in class.bcn_breadcrumb.php on line 121
```

Of course, I dug into the code a bit. Apparently, the warning occurs because the plugin is attempting to trim the URL. Here are the offending URLs:

- https://therenegadecoder.com/tag/python/
- https://therenegadecoder.com/tag/java/

However, all other tags seem to be fine:

- https://therenegadecoder.com/tag/data-structures/
- https://therenegadecoder.com/tag/georgia/

I've purged all my caches and whatnot, so I'm not sure what's going on. Any ideas? Thanks!

**Comment by jrg94** [comment]
I did a bit more digging on this. It appears the set_url input, URL, is an error and not a string: `Empty Term.` 

I'll keep digging, but I'm obviously not super familiar with the API. 😄

**Comment by mtekk** [comment]
The most likely cause of this that I can think of is `$wp_query->get_queried_object()` returns an empty string or null on those term archives. This isn't something that should be happening (and Breadcrumb NavXT can't really do its job if `wp_query` is borked).  I'd dig into why `$wp_query->get_queried_object()` is returning null.

**Comment by jrg94** [comment]
Sounds good! I'll take a look.

Btw, here's what those two tags looked like before I added the hacky workaround:

![image](https://user-images.githubusercontent.com/11050412/38846080-7095ddc8-41c8-11e8-8ed2-4a9cad65a944.png)

**Comment by mtekk** [comment]
Thanks for that update, I think I need to retract my previous statement. What may be the issue here is that there is still a term parent set for those terms. If you are feeling adventurous, try adding `var_dump($term->parent)` to just above line 553 in class.bcn_breadcrumb_trail.php, it would be interesting to see what that is in this case.

**Comment by jrg94** [comment]
You would be right! The two categories I converted were actually subcategories before they became tags. 

I ran that snippet above, and it returned: `int(322)`

All the other tags report `int(0)`. It seems there's still a linkage there.

**Comment by jrg94** [comment]
Not sure the quickest way to fix this issue, but I ended up just deleting the tags and adding them again. Seemed to do the trick. Thanks for your help!
