### ISSUE TITLE
Use primary category for breadcrumb

### ISSUE THREAD

**Issue by jrgong420** [mtekk/Breadcrumb-NavXT#217]
I am usually putting my posts in multiple categories.
How can I use the primary category for the breadcrumb?
Currently it seems, breadcrumb-navxt picks the first available one.

**Comment by mtekk** [comment]
How are you setting a primary category? Primary categories are not something that WordPress supports out-of-the-box, hence Breadcrumb NavXT does not support this out-of-the-box. The Breadcrumb NavXT Paths premium extension provides the ability to use a primary term (either though Yoast SEO, or a provided metabox).

**Comment by zeshanshani** [comment]
@jrgong420 or anyone else looking for the solution to show the primary category set by **WordPress SEO by Yoast** plugin, you can achieve this with the following code:

```PHP
/**
 * Breadcrumbs NavXT - Show Primary Category set by Yoast SEO
 *
 * @param $term – (WP_Term|boolean)(required) The term object returned by bcn_breadcrumb_trail::pick_post_terms() to filter (note that this parameter may be the boolean value false)
 * @param $id – (id)(optional) The ID of the post this term is for
 * @param $type – (string)(optional) The post type name for the post represented by the ID in the second parameter
 * @param $taxonomy – (string)(optional) The name of the taxonomy the term belongs to
 * @return mixed
 */
function zawp_navxt_primary_category( $term, $id, $type, $taxonomy ) {
  // Get primary category ID set by Yoast SEO.
  $primary_term_id = get_post_meta( $id, '_yoast_wpseo_primary_' . $taxonomy, true );
  
  if ( $primary_term_id ) {
    // get term against the primary category ID. 
    $primary_term = get_term( $primary_term_id, $taxonomy );

    // Check if it's not an WP_Error, and return the term.
    if ( ! is_wp_error( $primary_term ) ) {
      return $primary_term;
    }
  }

  return $term;
}
add_filter( 'bcn_pick_post_term', 'zawp_navxt_primary_category', 10, 4 );
```

You can modify this code easily to support other SEO plugins as well.

Cheers!
