### ISSUE TITLE
Uncaught Error: [] operator not supported for strings in ....../plugins/breadcrumb-navxt/includes/class.mtekk_adminkit.php:247

### ISSUE THREAD

**Issue by totallyben** [mtekk/Breadcrumb-NavXT#218]
We are seeing this fatal error with version 6.2.1.

This prevents plugins from being listed in Wordpress admin.

**Comment by mtekk** [comment]
This sounds like something doing something wrong with the `plugin_action_links` filter. Per the WordPress documentation for [`plugin_action_links`](https://developer.wordpress.org/reference/hooks/plugin_action_links/), the first parameter must be an array (hence the error). Try disabling other plugins and see if the issue persists.

**Comment by mtekk** [comment]
Due to lack of response from the reporter, I am going to close this issue
