### ISSUE TITLE
Structured Data Tool found Item missing in code

### ISSUE THREAD

**Issue by NakedPowerShell** [mtekk/Breadcrumb-NavXT#227]
![Misc_Tags_2019-10-01-16-28-31_Tags](https://user-images.githubusercontent.com/17523230/66007815-b66f7400-e468-11e9-8701-809fcaaa7a06.png)

Attached is the screen shot of the errors the GSDTT found.

Do you have any suggestions to fix this?

And all my WP, plugins, etc are all up to date.

**Comment by mtekk** [comment]
Double check your breadcrumb templates, it appears you are using the Microdata version of BreadcrumbList, which requires `itemprop="item"` in the anchor. See the Microdata example on https://schema.org/BreadcrumbList
