### ISSUE TITLE
Typo in bcn_breadcrumb_assemble_json_ld_array filter name

### ISSUE THREAD

**Issue by AndreyYevtukhov** [mtekk/Breadcrumb-NavXT#233]
Hi guys! 
Recently, I've found typo in `bcn_breadcrumb_assemble_json_ld_array` filter name.

---

In documentation [here](https://mtekk.us/code/breadcrumb-navxt/breadcrumb-navxt-doc/2/#bcn_breadcrumb_assemble_json_ld_array) and in release notes for version 6.2.0 [here](https://github.com/mtekk/Breadcrumb-NavXT) filter name is `bcn_breadcrumb_assemble_json_ld_array`.

But in code https://github.com/mtekk/Breadcrumb-NavXT/blob/master/class.bcn_breadcrumb.php | line 275 - it is called `bcn_breadcrumb_assembled_json_ld_array`.

---

For better comparing:
`bcn_breadcrumb_assemble_json_ld_array`
`bcn_breadcrumb_assembled_json_ld_array`

**Comment by mtekk** [comment]
Thanks for pointing this out. At this point, I'm thinking the best thing to fix this is to update the documentation and changelog (which I have done).
