### ISSUE TITLE
Clarification about bbPress paths

### ISSUE THREAD

**Issue by ajtruckle** [mtekk/Breadcrumb-NavXT#246]
Hi

I hope you are well. I noticed something today with the breadcrumb paths in bbPress (minor issue).

Here is the root:

https://www.publictalksoftware.co.uk/support-forums/
You are viewing Theocratic Software > Support Forum

Here is public forum group:

https://www.publictalksoftware.co.uk/support-forums/forum/general-information/
You are viewing Theocratic Software > Support Forum > General Information

Here is the public forum in that group (no user account required):

https://www.publictalksoftware.co.uk/support-forums/forum/general-information/frequently-asked-questions/
You are viewing Theocratic Software > Support Forum > General Information > Frequently Asked Questions

Here is one of the topics in that forum:

https://www.publictalksoftware.co.uk/support-forums/topic/how-do-i-subscribe-to-the-support-forums/
You are viewing Theocratic Software > General Information > Frequently Asked Questions > How do I subscribe to the Support Forums?

Can you see the subtle omission in the last breadcrumb trail? If I list them like this it might be clearer:

```
You are viewing Theocratic Software > Support Forum
You are viewing Theocratic Software > Support Forum > General Information
You are viewing Theocratic Software > Support Forum > General Information > Frequently Asked Questions
You are viewing Theocratic Software > General Information > Frequently Asked Questions > How do I subscribe to the Support Forums?
```

When we are displaying a topic it seems to miss out the root **Support Forum** entry in the trail.

**Comment by mtekk** [comment]
My gut feeling is that this is a settings issue, but I can't confirm right now due to my testbed server dying in an electrical storm. I'll look into this once I get my development environment back up and running.

**Comment by ajtruckle** [comment]
Thanks for having a look for me.

**Comment by mtekk** [comment]
Try setting the Root Page for the Topics post type to be the same as the Forums post type.

**Comment by ajtruckle** [comment]
Awesome. Seems to work well! Thanks.

I think we need a thorough bbPress setup help topic that covers some of these FAQs.

Thanks for your help.

**Comment by mtekk** [comment]
I'm currently writing an update for the Breadcrumb NavXT and bbPress Compatibility guide. It'll go live sometime later this month. This will be shortly after the updated Breadcrumb NavXT bbPress Extensions version is announced, which I hope to do within the next week or so.
