### ISSUE TITLE
Any plans for php 8.2

### ISSUE THREAD

**Issue by knut-erik** [mtekk/Breadcrumb-NavXT#286]
Hi,

Any plans for updating this to support PHP v8.2?

Tx

**Comment by mtekk** [comment]
The triathlete branch had fixes for php 8.2. This was released as Breadcrumb NavXT 7.2 today. If you are still running into PHP8.2 compatibility issues after updating to Breadcrumb NavXT 7.2 please let me know.

**Comment by knut-erik** [comment]
Thanks for the release!
