### ISSUE TITLE
Use taxonomy loop for all taxonomies

### ISSUE THREAD

**Issue by alleknalle** [mtekk/Breadcrumb-NavXT#294]
On my website I have disabled the default post_tag en category taxonomies. This causes the admin page of the plugin to break with a fatal error, since ``$this->form->textbox()`` requires the first argument to be of type ``mtekk\adminKit\setting\setting``, but it is ``null``.
In the code there is already a ``FIXME`` to use taxonomy loop for all taxonomies, just it's done for post. Could you implements this?

See https://github.com/mtekk/Breadcrumb-NavXT/blob/9d9b709c88fe272c672b35f68fe337b3056d807c/class.bcn_admin.php#L673

**Comment by mtekk** [comment]
Fixed in a943da1
