### ISSUE TITLE
Prioritize Taxonomy Terms

### ISSUE THREAD

**Issue by mtekk** [mtekk/Breadcrumb-NavXT#3]
Add support for plugins such as: http://wordpress.org/extend/plugins/hikari-category-permalink/ to allow prioritization of categories or other taxonomy terms. The default behavior for hierarchical taxonomies is to pick the first term hierarchy that is found. This behavior may not be ideal for all users. This extension plugin would modify this behavior with the help of Hikari Category Permalinks

**Comment by init-bobJames** [comment]
Great!

I'm using permalink categories for posts in multiple categories.

Couldnt figure out how to get breadcrumbs to link to the permalink'd, also slug url, as the breadcrumb would just be the first category by alpha i guess.

This plugin fixes, although I now have to specify permalink category twice, at least this does fix my issue!

Thank you @mtekk !

P.S. Whilst researching I did see a few comments saying you should nto have one post in multiple categories, and, that I'm doing it wrong! Finding out more would be great.
