### ISSUE TITLE
Typo: 'Tesxt to show before the trail'

### ISSUE THREAD

**Issue by jdvlpr** [mtekk/Breadcrumb-NavXT#301]
See [line 40 in /includes/blocks/src/breadcrumb-trail/edit.js](https://github.com/mtekk/Breadcrumb-NavXT/blob/aeb5ac44d1e8ffe47953987e75201fe3800c10da/includes/blocks/src/breadcrumb-trail/edit.js#L40)

Instead of 'Tesxt to show before the trail', I believe it should read 'Text to show before the trail'

**Comment by mtekk** [comment]
You are correct, it should have been "text" instead of "tesxt". Thanks for reporting this.
